---
- name: Create the users listed in the ipausers dictionary
  community.general.ipa_user:
    ipa_host: "{{ primary_ipaserver }}"
    ipa_pass: "{{ ipaadmin_password }}"
    name: "{{ users_item['name'] }}"
    givenname: "{{ users_item['givenname'] | default('-') }}"
    sn: "{{ users_item['sn'] | default('-') }}"
    mail: "{{ users_item['email'] | default(omit) }}"
    loginshell: "{{ users_item['loginshell'] | default(omit) }}"
    sshpubkey: "{{ users_item['sshpubkey'] | default(omit) }}"
    validate_certs: false
    state: present
  loop: "{{ ipausers }}"
  loop_control:
    loop_var: users_item
