- name: install cachefilesd
  ansible.builtin.apt:
    name: cachefilesd
    state: present

- name: Make sure the cachefilesd service is running
  ansible.builtin.systemd:
    name: cachefilesd
    enabled: true
    state: started

- name: Tweak the cachefilesd settings
  ansible.builtin.lineinfile:
    path: /etc/cachefilesd.conf
    regexp: "^{{ nfs_client_item['name'] }}\\s"
    line: "{{ nfs_client_item['name'] }} {{ nfs_client_item['value'] }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ cachefilesd_options }}"
  loop_control:
    loop_var: nfs_client_item
  when: cachefilesd_enabled
  notify: restart cachefilesd

- name: Enable cachefilesd
  ansible.builtin.lineinfile:
    path: /etc/default/cachefilesd
    regexp: '^#?RUN='
    line: "RUN={{ 'yes' if cachefilesd_enabled else 'no' }}"
    owner: root
    group: root
    mode: 0644
  notify: restart cachefilesd
