---
- name: Make sure that munge is enabled and started
  ansible.builtin.systemd:
    name: munge
    state: started
    enabled: true

- name: Add the munge key
  ansible.builtin.template:
    src: munge.key.j2
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0400
  notify: restart munge

- name: Make sure that slurmd is enabled and started
  ansible.builtin.systemd:
    name: slurmd
    state: started
    enabled: true
    daemon_reload: true

- name: Add the cgroup configuration file
  ansible.builtin.copy:
    src: cgroup.conf
    dest: /etc/slurm-llnl/cgroup.conf
    owner: root
    group: root
    mode: 0644
  notify: reload slurmd

- name: Add the GPU configuration file
  ansible.builtin.template:
    src: gres.conf.j2
    dest: /etc/slurm-llnl/gres.conf
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_local['gpu']['count'] is defined
    - ansible_local['gpu']['count'] > 0
  notify: reload slurmd

- name: Add the main configuration file
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: /etc/slurm-llnl/slurm.conf
    owner: root
    group: root
    mode: 0644
  notify: reload slurmd
